!function([t]){const i={r(){},d(t,i,n){t[i]=n}},n={};t.call(n,null,n,i);for(const t in n)n[t]=n[t]()}([function(t,i,n){"use strict";n.r(i);const e=11;function s(t,i){const{firstChild:n,lastChild:s}=function(t){return t.nodeType===e?t:{firstChild:t,lastChild:t}}(i);(n.lemnRef=t.i=n.lemnRef||t.i).t=n,(s.lemnEndRef=t.s=s.lemnEndRef||t.s).t=s}function r(t){const i=document.createRange();return i.setStartBefore(t.i.t),i.setEndAfter(t.s.t),i.extractContents(),i}function o(t,i){const n=r(t);s(t,i),n.insertNode(i)}function c({o:{t,l:i}},n){t.removeAttribute(i),Array.isArray(n)?t[i]=n.join(" "):"object"==typeof n?Object.assign(t[i],n):t[i]=n}function a(t){return t.some(Array.isArray)?a([].concat(...t)):t}const l="lemn";function h(t,...i){const n=[t[0],...a(i.map((i,n)=>[i,t[n+1]]))];let e;return Object.defineProperty(n,"content",{get(){if(!e){const t=n.map((t,i)=>"object"==typeof t||"function"==typeof t?`<link class=${l}${i}>`:t).join("")||" ";e=document.createRange().createContextualFragment(t)}const t=e.cloneNode(!0);return n.forEach((i,n)=>{if("object"==typeof i||"function"==typeof i){const e=t.querySelector(`.${l}${n}`);e?i.nodeType?o({i:{t:e},s:{t:e}},i):(i.lemnRef={...i.lemnRef,i:{t:e},s:{t:e}},t.h=[...t.h||[],i]):Array.from(t.querySelectorAll("*")).some(e=>Array.from(e.attributes).some(s=>{if(s.value===`<link class=${l}${n}>`){const n="class"===s.name?"className":s.name;return i.render?(i.lemnRef={o:{t:e,l:n}},t.h=[...t.h||[],i]):c({o:{t:e,l:n}},i),!0}}))}}),t}}),n}function u(t){return t.nodeType?t:h`${t}`.content}function m(t,i){t&&t.call(i)}function d(t){m(t.willDetach,t)}function v(t){m(t.didAttach,t)}function f(t){if(m(t.willRender,t),t.lemnRef.o)c(t.lemnRef,t.render()||"");else{const i=u(t.render()||" ");(t.lemnRef.h||[]).forEach(t=>!(i.h||[]).includes(t)&&d(t)),(i.h||[]).forEach(t=>f(t)),(i.h||[]).forEach(i=>!(t.lemnRef.h||[]).includes(i)&&v(i)),t.lemnRef.h=i.h||[],o(t.lemnRef,i)}m(t.didRender,t)}class P{constructor(t,i){this.parent=t,this.u=i,this.data=this.u(this.parent.data,this.data)}unbind(t){0===(this.m=(this.m||[]).filter(i=>i!==t)).length&&this.parent.unbind(this)}bind(t){1===(this.m=[...this.m||[],t]).length&&(this.parent.bind(this),this.data=this.u(this.parent.data,this.data))}push(){var t;this.data!==(this.data=this.u(this.parent.data,this.data))&&((this.m||[]).forEach(t=>t.push()),this.lemnRef&&(t=this,Promise.resolve(t).then(f)))}as(t){return new P(this,t)}willDetach(){this.parent.unbind(this)}didAttach(){this.parent.bind(this)}render(){return this.data}}class y extends P{constructor(t={}){super({bind(){},unbind(){},data:t},t=>t)}set(t){this.parent.data=t,this.push()}toJSON(){return this.data}}const $=new y(new Date);setInterval(()=>$.set(new Date),87);var p,D;p=document.querySelector(".root"),D=new class{constructor(t){this.model=t}pad(t,i){return this.model.as(i).as(i=>i.toString().padStart(t,"0"))}render(){return h`
    <section class="container" style="${{maxWidth:"20em",alignItems:"center",display:"flex",height:"100%"}}">
    <div style="${{fontSize:"2em",fontFamily:"monospace",textAlign:"center",width:"100%"}}">
      <div class="row">
        <div class="column">${this.pad(2,t=>t.getHours())}</div>
        <div>:</div>
        <div class="column">${this.pad(2,t=>t.getMinutes())}</div>
        <div>:</div>
        <div class="column">${this.pad(2,t=>t.getSeconds())}</div>
        <div>.</div>
        <div class="column">${this.pad(3,t=>t.getMilliseconds())}</div>
      </div>
    </div>
    </section>
    `}}($),p.appendChild(u(D)),f(D),v(D)}]);
//# sourceMappingURL=clock.js.map