!function([t]){const i={r(){},d(t,i,s){t[i]=s}},s={};t.call(s,null,s,i);for(const t in s)s[t]=s[t]()}([function(t,i,s){"use strict";s.r(i);const n=11;function c(t,i){const{firstChild:s,lastChild:c}=function(t){return t.nodeType===n?t:{firstChild:t,lastChild:t}}(i);(s.lemnRef=t.i=s.lemnRef||t.i).t=s,(c.lemnEndRef=t.s=c.lemnEndRef||t.s).t=c}function o(t){const i=document.createRange();return i.setStartBefore(t.i.t),i.setEndAfter(t.s.t),i.extractContents(),i}function e(t,i){const s=o(t);c(t,i),s.insertNode(i)}function h({h:{t,o:i}},s){t.removeAttribute(i),Array.isArray(s)?t[i]=s.join(" "):"object"==typeof s?Object.assign(t[i],s):t[i]=s}function r(t){return t.some(Array.isArray)?r([].concat(...t)):t}const u="lemn";function d(t,...i){const s=[t[0],...r(i.map((i,s)=>[i,t[s+1]]))],n=s.map((t,i)=>"object"==typeof t||"function"==typeof t?`<link class=${u}${i}>`:t).join("")||" ",c=document.createRange().createContextualFragment(n);return s.forEach((t,i)=>{if("object"==typeof t||"function"==typeof t){const s=c.querySelector(`.${u}${i}`);s?t.nodeType?e({i:{t:s},s:{t:s}},t):(t.lemnRef={...t.lemnRef,i:{t:s},s:{t:s}},c.l=[...c.l||[],t]):Array.from(c.querySelectorAll("*")).some(s=>Array.from(s.attributes).some(n=>{if(n.value===`<link class=${u}${i}>`){const i="class"===n.name?"className":n.name;return t.render?(t.lemnRef={h:{t:s,o:i}},c.l=[...c.l||[],t]):h({h:{t:s,o:i}},t),!0}}))}}),c}function l(t,i){t&&t.call(i)}function a(t){l(t.willDetach,t)}function f(t){l(t.didAttach,t)}function v(t){if(l(t.willRender,t),t.lemnRef.h)h(t.lemnRef,t.render()||"");else{const s=(i=t.render()||" ").nodeType?i:d`${i}`;s.lemnRef||((t.lemnRef.l||[]).forEach(t=>!(s.l||[]).includes(t)&&a(t)),(s.l||[]).forEach(t=>v(t)),(s.l||[]).forEach(i=>!(t.lemnRef.l||[]).includes(i)&&f(i)),t.lemnRef.l=s.l||[],e(t.lemnRef,s),s.lemnRef=t.lemnRef)}var i;l(t.didRender,t)}class m{constructor(t,i){this.parent=t,this.u=i,this.data=this.u(this.parent.data,this.data)}unbind(t){0===(this.m=(this.m||[]).filter(i=>i!==t)).length&&this.parent.unbind(this)}bind(t){1===(this.m=[...this.m||[],t]).length&&(this.parent.bind(this),this.data=this.u(this.parent.data,this.data))}push(){var t;this.data!==(this.data=this.u(this.parent.data,this.data))&&((this.m||[]).forEach(t=>t.push()),this.lemnRef&&(t=this,Promise.resolve(t).then(v)))}as(t){return new m(this,t)}willDetach(){this.parent.unbind(this)}didAttach(){this.parent.bind(this)}render(){return this.data}}class $ extends m{constructor(t={}){super({bind(){},unbind(){},data:t},t=>t)}set(t){this.parent.data=t,this.push()}toJSON(){return this.data}}const y=new $(new Date);setInterval(()=>y.set(new Date),87);!function(t,i){t.appendChild(d`${i}`),v(i),f(i)}(document.querySelector(".root"),new class{constructor(t){this.model=t}pad(t,i){return this.model.as(i).as(i=>i.toString().padStart(t,"0"))}render(){return d`
    <section class="container" style="${{maxWidth:"20em",alignItems:"center",display:"flex",height:"100%"}}">
    <div style="${{fontSize:"2em",fontFamily:"monospace",textAlign:"center",width:"100%"}}">
      <div class="row">
        <div class="column">${this.pad(2,t=>t.getHours())}</div>
        <div>:</div>
        <div class="column">${this.pad(2,t=>t.getMinutes())}</div>
        <div>:</div>
        <div class="column">${this.pad(2,t=>t.getSeconds())}</div>
        <div>.</div>
        <div class="column">${this.pad(3,t=>t.getMilliseconds())}</div>
      </div>
    </div>
    </section>
    `}}(y))}]);
//# sourceMappingURL=clock.js.map