!function([t]){const n={r(){},d(t,n,s){t[n]=s}},s={};t.call(s,null,s,n);for(const t in s)s[t]=s[t]()}([function(t,n,s){"use strict";s.r(n);const i=11;function o(t,n){const{firstChild:s,lastChild:o}=function(t){return t.nodeType===i?t:{firstChild:t,lastChild:t}}(n);(s.lemnRef=t.i=s.lemnRef||t.i).t=s,(o.lemnEndRef=t.s=o.lemnEndRef||t.s).t=o}function e(t){const n=document.createRange();return n.setStartBefore(t.i.t),n.setEndAfter(t.s.t),n.extractContents(),n}function c(t,n){const s=e(t);o(t,n),s.insertNode(n)}function r({o:{t,h:n}},s){t.removeAttribute(n),Array.isArray(s)?t[n]=s.join(" "):"object"==typeof s?Object.assign(t[n],s):t[n]=s}function h(t){return t.some(Array.isArray)?h([].concat(...t)):t}const u="lemn";function l(t,...n){const s=[t[0],...h(n.map((n,s)=>[n,t[s+1]]))];let i;return Object.defineProperty(s,"content",{get(){if(!i){const t=s.map((t,n)=>"object"==typeof t||"function"==typeof t?`<link class=${u}${n}>`:t).join("")||" ";i=document.createRange().createContextualFragment(t),s.forEach((t,n)=>{if("object"==typeof t||"function"==typeof t){const s=i.querySelector(`.${u}${n}`);s?t.nodeType?c({i:{t:s},s:{t:s}},t.cloneNode(!0)):(t.lemnRef={...t.lemnRef,i:{t:s},s:{t:s}},i.u=[...i.u||[],t]):Array.from(i.querySelectorAll("*")).some(s=>Array.from(s.attributes).some(o=>{if(o.value===`<link class=${u}${n}>`){const n="class"===o.name?"className":o.name;return t.render?(t.lemnRef={o:{t:s,h:n}},i.u=[...i.u||[],t]):r({o:{t:s,h:n}},t),!0}}))}})}return i}}),s}function a(t){return t.nodeType?t:l`${t}`.content}function f(t,n){t&&t.call(n)}function d(t){f(t.willDetach,t)}function p(t){f(t.didAttach,t)}function $(t){if(f(t.willRender,t),t.lemnRef.o)r(t.lemnRef,t.render()||"");else{const n=a(t.render()||" ");n.lemnRef||((t.lemnRef.u||[]).forEach(t=>!(n.u||[]).includes(t)&&d(t)),(n.u||[]).forEach(t=>$(t)),(n.u||[]).forEach(n=>!(t.lemnRef.u||[]).includes(n)&&p(n)),t.lemnRef.u=n.u||[],c(t.lemnRef,n.cloneNode(!0)),n.lemnRef=t.lemnRef)}f(t.didRender,t)}class m{constructor(t,n){this.parent=t,this.l=n,this.data=this.l(this.parent.data,this.data)}unbind(t){0===(this.m=(this.m||[]).filter(n=>n!==t)).length&&this.parent.unbind(this)}bind(t){1===(this.m=[...this.m||[],t]).length&&(this.parent.bind(this),this.data=this.l(this.parent.data,this.data))}push(){var t;this.data!==(this.data=this.l(this.parent.data,this.data))&&((this.m||[]).forEach(t=>t.push()),this.lemnRef&&(t=this,Promise.resolve(t).then($)))}as(t){return new m(this,t)}willDetach(){this.parent.unbind(this)}didAttach(){this.parent.bind(this)}render(){return this.data}}class y extends m{constructor(t={}){super({bind(){},unbind(){},data:t},t=>t)}set(t){this.parent.data=t,this.push()}toJSON(){return this.data}}function b(t){return t.toString().replace(/</g,"&lt;").replace(/>/g,"&gt;")}class w{constructor(t={}){this.options=t}render(){const{name:t,placeholder:n,model:s}=this.options;return l`<input type="text"
      name="${t}"
      placeholder="${n}"
      value="${s.data}"
      onkeyup="${t=>s.set(t.currentTarget.value)}">`}}!function(t,n){t.appendChild(a(n)),$(n),p(n)}(document.querySelector(".root"),new class{constructor(){this.name=new y("")}render(){return l`
      <section class="container" style="margin-top: 2em">
      ${new w({placeholder:"world",model:this.name})}
      <div>hello ${this.name.as(t=>t||"world").as(b)}</div>
      </section>
    `}})}]);
//# sourceMappingURL=helloworld.js.map